### ISSUE TITLE
What does the email function do?

### ISSUE THREAD

**Issue by doducquang** [xxFlare/xAuth#14]

**Comment by xxFlare** [comment]
It requires users to type there email while registering... but it's not added yet!

**Comment by NGGNewGen** [comment]
Hey xflare its me again i was wondering if you can make a death messages plugin like where it says player has been slain by player2 can you make a plugin to where thats editable?

**Comment by NGGNewGen** [comment]
Because im running a netherbox server and i cant edit that :/

**Comment by xxFlare** [comment]
@NGGNewGen That is a plugin request.

This is a place to open issues for xAuth.

**Comment by NGGNewGen** [comment]
A vps hm i might do that thank u!! :)
