### ISSUE TITLE
Single password to login on all account

### ISSUE THREAD

**Issue by Jackboy320** [xxFlare/xAuth#15]
Original text: 

>  that is a feature request Can you add a option in the config 1-time-password: Hnifrunvfd
> And if a Admin or a Player types this password with a  another account this password will then always be acceptet

edited version by @PEMapModder:
This issue requests for a feature where a certain password specified in config can be used to login on all accounts, like a sudo password on Linux for doing `sudo su`.

**Comment by ChiefArtz** [comment]
?

**Comment by PEMapModder** [comment]
Edited the description. Check if it is what you meant

**Comment by xxFlare** [comment]
I think this feature would be easily abused by server owners. Also it will make people not trust xAuth to use as there authentication plugin.

**Comment by PEMapModder** [comment]
I don't think this increases any abuse. A server owner can simply temporarily delete the record of the player if they want to login as them.

**Comment by Jackboy320** [comment]
Ok
