### ISSUE TITLE
eating bug

### ISSUE THREAD

**Issue by Driesboy** [xxFlare/xAuth#18]
Fatal error: Call to undefined method pocketmine\event\player\PlayerItemConsumeEvent::getEntity() in phar:///Users/Ronny/Desktop/pocketmine/plugins/xAuth_v1.0.0.phar/src/xFlare/xAuth/LoginTasks.php on line 144

**Comment by Driesboy** [comment]
PocketMine-MP Crash Dump Wed Dec 2 11:42:55 UTC 2015

Error: Call to undefined method pocketmine\event\player\PlayerItemConsumeEvent::getEntity()
File: /xAuth_v1.0.0.phar/src/xFlare/xAuth/LoginTasks
Line: 144
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: xAuth v1.0.0

Code:
[135]         if($this->plugin->status === "enabled" && $this->plugin->loginmanager[$event->getEntity()->getId()] !== true && $this->plugin->allowShoot !== true && $event->getPlayer() instanceof Player){
[136]             $event->setCancelled(true);
[137]         }
[138]         elseif($this->plugin->safemode === true and $this->plugin->status !== "enabled"){
[139]     		$event->setCancelled(true);
[140]     		$event->getPlayer()->sendMessage($this->disable);
[141]     	}
[142]     }
[143]     public function onFoodEat(PlayerItemConsumeEvent $event){
[144]         if($this->plugin->status === "enabled" && $this->plugin->loginmanager[$event->getEntity()->getId()] !== true){
[145]             $event->setCancelled(true);
[146]         }
[147]         elseif($this->plugin->safemode === true and $this->plugin->status !== "enabled"){
[148]     		$event->setCancelled(true);
[149]     		$event->getPlayer()->sendMessage($this->disable);
[150]     	}
[151]     }
[152]     public function onJoin(PlayerJoinEvent $event){
[153]         if($this->plugin->status === "enabled" && $this->plugin->join !== true){
[154]             $event->setJoinMessage("");

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #0 [Protocol 38; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Darwin iMac-van-Ronny-8.local 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64
PHP Version: 5.6.10
Zend version: 2.6.0
OS : Darwin, mac

Loaded plugins:
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
GameCraftPE 1.1.0 by TheDeibo,Driesboy for API(s) 1.10.0
GCPESocial 1.0.0 by  for API(s) 1.10.0
NetherChests 1.1.1 by aliuly for API(s) 1.12.0
PurePerms 1.2.2 by 64FF00 for API(s) 1.12.0
xAuth 1.0.0 by xFlare for API(s) 1.8.0
1vs1 0.0.3 by  for API(s) 1.0.0, 1.1.0
PureGIS 1.0.0 by 64FF00 for API(s) 1.12.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNWgtz2za2/itYpbNr74iyqJdtZZwZj+10s5s03tjZ3Jmq4wFJUGJNEixBWlY7ub/9fucApCjF
6aZpd/a6DwkgcPCd9zmgfulVSaZ6c38yOR1OZ9Pjab+nylKXvfkvvWpT4FHv6u7q3bu373r9XqaM
kUuau5BpKiot6jxScZKrSGSqWulIFDq8V1WGqcVCPai8WiyKVG5UuVhc8+erSmUXOjd1pq7o+Xy+
VNVVXiXV5uAQZ8RJSgccPZ7X1eruwR8M8U+xkuWRKcOjx5epLJV9ePRaL5P8Vpp7g30pjmQ+PvZ7
RVrjCajwOjwMdaSII388xaxwf0l88E21Soz3wm7wXphKVrURZ2dnYtFTuQxSFS164s9/FnsLUzo6
kzmkUX7/DTPqvegwwoNX0cHhD+JPIFaVtXqCCoSo1zcrravdVVt6VmYHhyLJgS0PlY6FnTv8BXz5
41mHH/pr9hpVXdD6FBwcEOHD57z+uLP+I8+cdGZUatQTUpGxyiBBlguDlHkknhbdn3ZF51CeujMW
1aL6NwgnwyfWdiRBG/PojbXEBmmUGDrQUfBbCszhZOTGdjR2o6IO0iQUcZ2HVaJzofOXWkdXsjp4
2lCdaC1Hk8l/zY4cgOlvU/xktq/4yfF/XvGTk9+g+NPfq/jpcFfxU7+r+Onos4r/u05yp3X6+qm6
p+M/Rt0/gvqeIqeTzyuSwDQML3oQ6vMeoltVyhDR7Pves6E4OJzvhNwbVT6o0nsRltKsLuusOAi0
TpXMD3s/9HtLlatSphQJscqAeZztD2aRegCUoE7SqDcfIn6WutKhxsLxSb8ni4SX+ePBEMuWSYXh
8Av/sKGU92kS0J7BMVOoc0k5p3cpyzXkkbyRofcgc++dzvONdzJIdShT4U8p9Au36B+qzFUq/mVh
u4dzcSMrcaMK4Z9iaj4dzyczcX15K0ZDf/pclIis88e89sajyfHAHw58/3/9o3dXr6/Ob67u/udk
djebiEf+AKxiVQDUdDDDSgx/hrVhPMJ4aJ/eadOixgyPMhn22oxjSLKX6uEWMufvDaPNVH9H7gBE
lCVylC4NafSaVfkGqhS3SmakM5b+91g9Hvg0dubVm5MJ9XuRKoCTNuOZ0XF12Z3IJKfB5vzFooMk
1ZL4u7k9f3f7/hoTaxWYpCK8q6oqzPzoCKpe1cEg1NnRFtlRSwN8X4U619nm/PpVh93OZJfhEVR2
usuvzlWA/3b4tEKBdNznqP30+XPsxmM3nrjx5Ovl42CgYrHIgWWx2OHCCev67c3th7fvXl92xZXX
aQpRfAvmL0oZV9dXHVl0Z/e0v6/825W6VEmg+5dlokygNztiYWP5Sv46IBaLN5Kt90s4uri+utFh
YiNGw9B2cpeffWP+L4P/DvWoKi9WylRdV9yZ3leIv6sQmSZ1uqeF0dczYsktFrkK6fgvYuYpV5Sp
+hF5uNSgd7QN/p6LQUdVqdRRJk2lyqMddiGV67pU16rMuiLZzu3KYzQY7cpjNnn5cjj8w+RxZ+mh
MWgAdL7+9gBFO50EtlTAsu0Btuw2PcGv2W7P9hk7rJ58PaeW2mLBRy8Wr8GYKr/MjP0H43fA87CL
nbqj8Wf9rhtLvxI7Qn4SJ4+JXiwQIh8Mx8m3ufqXwf++jAdSx7evbvZMjmb+jRb+kwaH49svv9vY
iMZHKgNkCQbheA0SLscGqKcKVVaI6iD37LodCfQXcbIU1PMuykX+7AMa6UsVipHw/fn4dD49Fu9v
L7iaoeeWnEdCPKNUHFJYnIvrK2Hrvs6aQpfVmX/qj0c0ucQOKuTPhjTK5KNnm3JzNuIZU8h17lHZ
p7gmPvNnNL1eQQJempjqTMcxzVixez/Vqtyc6bwzVSJdNqsyXUWfBSjzXKP0Vg6CJ8NVgpI3Q9Fr
HEnui704TZar9mQLUeZJJtNmnZ3LdNBMxLoE4ZZbt3UlyyjUZTsuHgq3PkriOAnrtNqc+SwnLpAr
XXqovqskX5ozmk6BL7ViX+syjbZzRqmos4RuTM4ur16ev399S7MklEEhjcG26Oyv/Af26kp7Rj4o
h4KqyzaMDzZZSlYiKDuIkA2kBiaqeslOBHgU22rMe3MNuxGoHYwSDWiBaCMQ+NHawMiqFYrkkMRe
iUCJJA/TOoKhgfwn9km0bnSGnTER2KdJDWFfaMophkiKoFTyXmx0XTpa6I4EZI+QwSdA7CVMCmkP
hL9T65bcUaRiCcEbsdb5Xyohi0LJUpBoMjCLBiDdAL6g/snyvV6pXNTFspQRCAwWOdm6JTZf5OLZ
7Qp5z0sxBRSpzJc12iZBNz8sMucXJsGYG4zkZxYqbUV+DB0XuxsBoPF+lQ/WyX1SqCiRA10uj2h0
9Bq+cafju1c3b+9m41NvdEf7IMaW0JxbwiXaNxz0YcX5mG7OqJkVdItmqpLli7YuN6msIDd+zNJk
pMCBb6pilaJXS0IlVqgAUlZyBsLW7rdHxvARhXmzqqtIk4/YLpLAWE8UYaoNdakE65z8TZCfA4lw
dYR4SKT4Jzk6lrDDNxXGnNtX2nizwj5JVmrQZQp3ilWVdIREbWCECNAwBOYOFbW7LSQ5bR94gBUA
1Jb8FYeWhg7dPZAbC5grLIKgBhvh7AjLXSBqn27F8OxDAkHrHCYlo0iUyljLI5iwtXvAkQZhnGKQ
gL0FiuQBoaufasn3nMsETbl4kGmtxIE7EmH5EMTteQiAimKuB20ul6qc4ymd/F2dBZA23OncbPKQ
bith8eU9HGhAz99DCWyfDZO0alWi9ahhEnS32Rccc4SLTTDZPsSQQWqGW2ESC5IVzWV1Ds+hJUz7
hk0G/MC5Sv2IyFkpiADssKnnLTSSqoXzKiYPpSXkiX2RVH+hi96Sd0WK0gNb4d5ecQAOoGcxIokw
D57jcs6UyFspKJcb9tVvUx1AsJSohZ2G9WVJRTEpU0sZbCoAEjcWypAPtzc91tPB0zphYCxsQenC
0mnkb1gucVLSnZXgKxWiEiNGNCda9YOZmo12qcGHJtcgmeGcJYP0GNhcDBccKjgqVwg1Mvp/Dp+K
nl8BT0nxd4E3lS74fBeqWjyOmhFwKcp9iDIODZ3ZQPKHo4lFhUo90ZyOyBcNHRhyQHboWn/zcRRC
TUQ2xis8+IOynsZhXOcIYPBQyI2iw+fEasWJ4iblCE++bpctOOESDXjf1pNtOKIT3lIIoQzHywef
Lia2XWkKERYqpERoWCyE1crY7m0ZgCRVYbZsjoeOT3P4JCDH9dhyvZRlAP17oU5TW7yRhz0pVTYn
guL2CLcHvpvJvOaU20WBcqSGLRz2m5iwZwzOGmxcjeMmNmRbKxuItzbf8QgWsdJ1GrVAEkSQdS62
0MluRcHIweBsOLQ8imcv2RM+iY1sK3Z3y1Rc6qwJsbTXPfe6UamjUzDhVLdvCk/YT2cfFdHhqs7v
jZX3a7Z6Cog8SciopyBuhK10++yeJQoQYxd5VANQLbOlRaQaNTtHOZ05nJfabttXn73DbrZ1KdhT
3LI/gGdORF4o6f6CuXa20BxED9rs/aukFnmuKtJFW7rBNFKbCQNZoSWgQkRSlYsECHtyUYkd0Bam
7qkNRoFqcyKHm2fd8NU8IccvNxXR7gvP7xgz5T4+1qsaKAgr05mNKttcy1U+JbrIhjunQLsXkw7T
QPwNrQvEe4ZaGIZ7cf2+j71AECD+rJOoWtmozf7dkveY/Fwcu8JgWzIYFkxn6UCcR/CnlUzjIxT5
toqJFOzMHYQjrf3pvOuQbXbu0OrUSVeP5HxUBsm0bx2bDv6Q5KgiwdZtydFMc65/f51fN5XCtman
Iog2rRHrF1Sw54Xnht2aDL2XCurl3BUdL4RPxYbLLFRV8uOmojQcx1aqqTQXThVII9s60Ygj+yKm
L46WoRUt4lpkOoc2XdtO36CaIpJwgxPbMfFSZ17ELis8hBArtjC3xbNb5iLDo6XrJ8AQX0sQXJgc
jJSDktyhj8hJHVnVOR7CrD5Fwz7Kqnv23dvbq7ngqIt/wxrNVY7migklWZFyBcvw3MktvFbF5zva
CtFHIJI4XtmKOCUBCVlNRZYzGroUQqHMZiYyI2piad6lI+f1u9NNDLO18A25KzEYSKM6hx34cJQn
TumLER74Tz1QVTg4ZKc1qouCzeGWKFNr5S45hEJgsudR6rea5CZ2291SIOAuiKonCgcyXcuNsbQd
nY4d7cRvNqPzTNd5NwEYV7M1IAg+UaOWAbGZvs7F5PNbZYnZyGJ3P6HYyTrCPx09uZutK1e2jwyU
pRaomCIR35hQxCI1tFTtPUon9NnIdyMfkHSpvkuoXVbUfhUbdzXgclFb0HCgiPnWuQmLLozFdcrL
tIGpeuSiSWhTCbdgJfXjMAyQbUTFr0ml9Q0jM7KVjGMlJZiW/z1lkEAbZbyRj0LuywU9UMj5YWsP
u7pgI30no6Q2nW1OD9KhYye1W53d0XpUKxST6MLKq4sItrgFiFZbSXsI36Vts6AFvm3sGuyDT8G7
+LeWCffo6Mdr5fTr9rPb87xnoKy5OPkqaoUu6tRRc98pNe0RXuTskx6kR6DttZzHdmRIkiTKDLG6
oisXN+u78EA3X3Nhi7tGpfSKui5Q7NiKzxokBw9baDhaoHJMu9yBRHRKw7Wkg9pJnpNZkNDvi3iJ
u3SzPfrcBiO6TqDX5MLO2hzrjMRar6vk2+BGdu3RBc/uTJtOdmaLVZHksd6awUqT7vnIQee+D4UQ
48t1vsmozGcPMZCvaYFS3+Iei+1jBgxbk0Iul8g+7nKgvXahGpF+LHD/NDcWD5EzT+EheVlTZhXv
74ZN2Kdzq4Ay91xy3laAPKuLzoXRBd0Z8iWWSnVB2aqPMTigG7qqKcVQmcSolBWEjfyUU56nRS61
1qQd+GOHiHCvETo1RI2C01Q2wTUBz1EjDdnHDX2zJ5T1ev2USNIE6cZq5epRUr61AypYQN+BmDdo
+BGMnTrlufievnpIMn1unX8gijYKNmVI97aVmWj6Bdu0NXfT3I09dXnLzS1nMcMVA7GdoZBIANSl
+A50PpUB8DdBV9nkupyStqfNxcvX57fz0fPj/vT00e+PH8f90XP/eYRMbKPWAb1wDCnCnJ0MxRL2
bexoMj3ky231WKmcBMJvHS+Qh7q/syAb6o6REJa9OTtNv1eEtNgNzE9pUqmx/SWJZ3+08rP9aYn9
kUAQorJZtevp6jSPZLmdsL9obEZ1mbaDOElh6Ezat2/m46pony6j7ddsO72CK9s3V1j/o2nfm9Ir
uiywF7vtYhSIm6LaMlNJwhZ1Wb+5fs0I6L1rEaKy227egHn+PYr7JugHML5PUhAevSAaDafDMb5+
84pa53B2chLMgiAcD6PxTMZjGY4ncRRNguNgGhyfHMdqij/xDU66XpGI+OcZfLA2yeNWAa51dwt8
Yu2dil3fiVk+T8XxSRCFs2kwDJSMT+KJjNQsHs7ik8mJmkWTcRRHJ6MZn2dWmd7K0LCbmV1OE6sI
LK70vcqRdcp25oOS94gPVlCDGWY2kl+ZNG/wf04KOxoNpr2PH/8PQ4qLEg==
===END CRASH DUMP===

**Comment by ChiefArtz** [comment]
ye ik

**Comment by xxFlare** [comment]
Should be fixed now. Let me know if it is :)

**Comment by ChiefArtz** [comment]
oki
