### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by Driesboy** [xxFlare/xAuth#19]
now you have automatic xauth
can you make it that you can change the name 
![image](https://cloud.githubusercontent.com/assets/15795262/11534124/6fc4573c-990d-11e5-9924-b99085e8eb7e.png)

**Comment by ChiefArtz** [comment]
yes u can. if xauth fully released i think so.

**Comment by xxFlare** [comment]
Added!

**Comment by Driesboy** [comment]
ok thx
