### ISSUE TITLE
Non-existent hashing algorithm

### ISSUE THREAD

**Issue by Gamecrafter** [xxFlare/xAuth#2]
Where did you find the hashing algorithm "xauth"? This algorithm is non-existent, I've looked everywhere and I can't find it. If it exists, link me to it. If not, you should look at a [list of hash algorithms](https://en.wikipedia.org/wiki/List_of_hash_functions).

**Comment by PEMapModder** [comment]
You can find a list of algorithms from [`hash_algos()`](//php.net/hash-algos)

**Comment by xxFlare** [comment]
Fixed in latest commit.
