### ISSUE TITLE
how to use MySQL?

### ISSUE THREAD

**Issue by ChiefArtz** [xxFlare/xAuth#23]
??

**Comment by xxFlare** [comment]
https://github.com/xxFlare/xAuth/blob/master/resources/config.yml#L7

It should be set automatically.

**Comment by ChiefArtz** [comment]
how do we do the config? i mean for mysql

**Comment by xxFlare** [comment]
MySQL is not added just yet.

The plugin has been set up in a way that I can easily add it, just need to find the time to.

**Comment by xxFlare** [comment]
You can use YML right now - It's faster, easier, and convenient.

**Comment by ChiefArtz** [comment]
how to do the config .-.

**Comment by xxFlare** [comment]
I'm not sure what your question is..Do you mean how do you set up MySQL? (When it's added)

**Comment by PEMapModder** [comment]
He mentioned yml...

**Comment by ChiefArtz** [comment]
how to setup YML?

**Comment by xxFlare** [comment]
@ChiefArtz
"https://github.com/xxFlare/xAuth/blob/master/resources/config.yml#L7

It should be set automatically."

**Comment by ChiefArtz** [comment]
.-. i have two servers i wenna trasfer the files to same time

**Comment by PEMapModder** [comment]
@ChiefArtz change YML to MySQL, and fill in the MySQL details in the following lines.

**Comment by xxFlare** [comment]
Then you need mySQL not YML.

First, this is not implemented yet. So in other words, you can't use mySQL with xAuth.

**Comment by xxFlare** [comment]
Seems like you want MySQL not YML.

MySQL has not been added yet.

**Comment by ChiefArtz** [comment]
i said yml

**Comment by PEMapModder** [comment]
Race conditions will occur if you use the same YAML files for multiple servers.

**Comment by ChiefArtz** [comment]
me dunt understand

**Comment by xxFlare** [comment]
If you want to use YML on both servers.. You would have to transfer all files between registering and logins.

MySQL is nottransfering YMLs...It's a different way to store data/fetch.

**Comment by PEMapModder** [comment]
If you use the really same files, two servers will overwrite the changes on either server.
