### ISSUE TITLE
When will MySQL Support addeded ?

### ISSUE THREAD

**Issue by Underpippo** [xxFlare/xAuth#26]
Hey,

first of all, it's a wonderful Plugin :D 
Much better then SimpleAuth !
But I have one Question :D When do you support MySQL ? 

Thanks 
Underpippo :D

**Comment by xxFlare** [comment]
It will be added hopefully this weekend!

**Comment by Underpippo** [comment]
Nice :D How can I support you ? For example with money etc. ?
